version: '3.8'

services:
  recommend:
    build:
      context: .
      dockerfile: ./recommend/Dockerfile.dev
    container_name: ecom-recommend
    depends_on:
      - database
      - cache
    volumes:
      - ./recommend:/usr/src/app
    environment:
      - APP_HOST=${REC_HOST}
      - APP_PORT=${REC_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REC_COUNT=${REC_COUNT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - ${REC_PORT}:${REC_PORT}
    networks:
      - ecom_net

  webserver:
    build: ./webserver
    container_name: ecom-webserver
    volumes:
      - ./webserver/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - database
      - cache
    networks:
      - ecom_net
    ports:
      - 80:80

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: ecom-frontend
    volumes: 
      - ./frontend:/usr/src/app
    ports:
      - 4200:4200
    networks:
      - ecom_net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: ecom-backend
    volumes: 
      - ./backend:/usr/src/app
    depends_on:
      - database
      - recommend
    environment:
      - APP_PORT=${APP_PORT}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PSWD_HASH_SALT=${PSWD_HASH_SALT}
      - SECRET=${SECRET}
      - TOKEN_EXPIRES=${TOKEN_EXPIRES}
      - REC_HOST=${REC_HOST}
      - REC_PORT=${REC_PORT}
    ports:
      - 5000:5000
    networks:
      - ecom_net

  cache:
    build: ./cache
    container_name: ecom-cache
    restart: always
    networks:
      - ecom_net

  database:
    build: ./database
    container_name: ecom-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - db-data:/data/db
    networks:
      - ecom_net

volumes:
  db-data:

networks:
  ecom_net:
